#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Raise the NameError exception and asign message."""
    raise NameError(message)
